### ISSUE TITLE
aim50-1-6-yes1-2: KeyError

### ISSUE THREAD

**Issue by prwang** [prwang/simpleCDCL#1]
<pre>
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 45, in main
    if fm.solve():
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 232, in solve
    while not self.step(): pass
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 213, in step
    if self.bcp():
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 133, in bcp
    self.assign(abs(m), m > 0, y.defined)
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 72, in assign
    x = cl.def_(_var * (-1 + 2 * role))
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 19, in def_
    self.undef.remove(other) #FIXME keyError:
KeyError: -5
</pre>

**Comment by prwang** [comment]
Error when vars of both side exist at the same time.
fixed by adding special cases a740ca2f7e1dad47eff9d03537ae3c433ab58eb4
