### ISSUE TITLE
assertion failed on ./testfiles/aim/aim-50-1_6-no-2.cnf

### ISSUE THREAD

**Issue by prwang** [prwang/simpleCDCL#2]
<pre>
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 45, in main
    if fm.solve():
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 236, in solve
    while not self.step(): pass
  File "/mnt/d/Documents/L_PV/simpleCDCL/formula.py", line 223, in step
    assert self.zero
AssertionError
</pre>

**Comment by prwang** [comment]
empty learned clause indicates an unsat.
